version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "0915051590"
      POSTGRES_DB: render_backup
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: node_api_app
    restart: always
    ports:
      - "3100:3100"
    env_file:
      - .env
    depends_on:
      - db
volumes:
  postgres_data:
