version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: node_api_app
    restart: always
    ports:
      - "127.0.0.1:3100:3100" # Chỉ cho phép truy cập nội bộ từ Nginx
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: